<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xml.netbeans.org/schema/BpelVerifyEmployeesStatus" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/BpelModule/src/BpelVerifyEmployeesStatus" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BpelVerifyEmployeesStatus" targetNamespace="http://j2ee.netbeans.org/wsdl/BpelModule/src/BpelVerifyEmployeesStatus">
  <types>
    <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BpelModule/src/BpelVerifyEmployeesStatus">
            <xsd:import namespace="http://xml.netbeans.org/schema/BpelVerifyEmployeesStatus" schemaLocation="http://daniels-mbp:9080/CompositeApp-sun-http-binding/BpelModule/BpelVerifyEmployeesStatus.xsd"/>
        </xsd:schema>
  </types>
  <message name="BpelVerifyEmployeesStatusOperationResponse">
    <part name="response" type="ns:verifyEmployeesStatusResponseDto">
    </part>
  </message>
  <message name="BpelVerifyEmployeesStatusOperationRequest">
    <part name="request" type="ns:verifyEmployeesStatusRequestDto">
    </part>
  </message>
  <portType name="BpelVerifyEmployeesStatusPortType">
    <operation name="BpelVerifyEmployeesStatusOperation">
      <input message="tns:BpelVerifyEmployeesStatusOperationRequest" name="input1">
    </input>
      <output message="tns:BpelVerifyEmployeesStatusOperationResponse" name="output1">
    </output>
    </operation>
  </portType>
  <binding name="BpelVerifyEmployeesStatusBinding" type="tns:BpelVerifyEmployeesStatusPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="BpelVerifyEmployeesStatusOperation">
      <soap:operation/>
      <input name="input1">
        <soap:body namespace="http://j2ee.netbeans.org/wsdl/BpelModule/src/BpelVerifyEmployeesStatus" use="literal"/>
      </input>
      <output name="output1">
        <soap:body namespace="http://j2ee.netbeans.org/wsdl/BpelModule/src/BpelVerifyEmployeesStatus" use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="BpelVerifyEmployeesStatusService">
    <port binding="tns:BpelVerifyEmployeesStatusBinding" name="BpelVerifyEmployeesStatusPort">
      <soap:address location="http://daniels-mbp:9080/BpelVerifyEmployeesStatusService/BpelVerifyEmployeesStatusPort"/>
    </port>
  </service>
    <plnk:partnerLinkType name="BpelVerifyEmployeesStatus">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BpelVerifyEmployeesStatusPortTypeRole" portType="tns:BpelVerifyEmployeesStatusPortType"/>
    </plnk:partnerLinkType>
</definitions>
